cloud: 
  aws: 
    s3: 
      bucket: bunnyfoot-s3 
    region: 
      static: ap-northeast-2
    stack: 
      auto: false 
    credentials: 
      instanceProfile: true
      accessKey: ${S3_ACCESS_KEY} 
      secretKey: ${S3_SECRET_KEY}